Updated secuirty.yaml file

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -27,6 +27,7 @@ jobs:
       - name: Run tests
         run: npm test
 
+
   snyk-sca:
     name: Snyk SCA
     runs-on: ubuntu-latest
@@ -52,38 +53,51 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
+      - name: Upload Snyk SCA JSON report
+        uses: actions/upload-artifact@v4
+        with:
+          name: snyk-sca-report
+          path: snyk.json
+
+
   snyk-sast:
     name: Snyk SAST
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: 20
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
 
-    - name: Install Snyk CLI
-      run: npm install --global snyk
+      - name: Install Snyk CLI
+        run: npm install --global snyk
 
-    - name: Confirm Snyk installation
-      run: snyk --version
+      - name: Confirm Snyk installation
+        run: snyk --version
 
-    - name: Confirm Snyk token exists
-      shell: bash
-      run: |
-        if [ -z "$SNYK_TOKEN" ]; then
-          echo "SNYK_TOKEN is missing"
-          exit 1
-        fi
-        echo "SNYK_TOKEN is available"
-      env:
-        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - name: Confirm Snyk token exists
+        shell: bash
+        run: |
+          if [ -z "$SNYK_TOKEN" ]; then
+            echo "SNYK_TOKEN is missing"
+            exit 1
+          fi
+          echo "SNYK_TOKEN is available"
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-    - name: Run Snyk Code scan - SAST
-      if: ${{ !cancelled() }}
-      run: snyk code test --severity-threshold=high --debug
-      env:
-        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - name: Run Snyk Code scan - SAST
+        if: ${{ !cancelled() }}
+        run: snyk code test --json > snyk-code.json
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+      - name: Upload Snyk SAST JSON report
+        uses: actions/upload-artifact@v4
+        with:
+          name: snyk-sast-report
+          path: snyk-code.json
